### ISSUE TITLE
Stack trace in naiserator-webhook

### ISSUE THREAD

**Issue by sechmann** [nais/naiserator#503]
`naiserator-webhook` logs the following stack trace in all environments and when running locally.
```
Detected at:
        >  goroutine 28 [running]:
        >  runtime/debug.Stack()
        >       /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
        >  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
        >       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xcd
        >  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc000053240, {0x18d3b5c, 0x9})
        >       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:147 +0x45
        >  github.com/go-logr/logr.Logger.WithName(...)
        >       /go/pkg/mod/github.com/go-logr/logr@v1.3.0/logr.go:349
        >  sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).getLogger.func1()
        >       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/webhook.go:182 +0x66
        >  sync.(*Once).doSlow(0x0?, 0xc000451220?)
        >       /usr/local/go/src/sync/once.go:74 +0xbf
        >  sync.(*Once).Do(...)
        >       /usr/local/go/src/sync/once.go:65
        >  sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).getLogger(0xc00018f220, 0xc0000c8000?)
        >       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/webhook.go:180 +0x4d
        >  sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc00018f220, {0x7f30dc815460?, 0xc0002b4410}, 0xc000222100)
        >       /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/webhook/admission/http.go:96 +0xbab
        >  sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1({0x7f30dc815460, 0xc0002b4410}, 0x1b44900?)
        >       /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:60 +0xcb
        >  net/http.HandlerFunc.ServeHTTP(0x1b44930?, {0x7f30dc815460?, 0xc0002b4410?}, 0xc0001ff8a0?)
        >       /usr/local/go/src/net/http/server.go:2136 +0x29
        >  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1b44930?, 0xc000208000?}, 0xc000222100)
        >       /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:147 +0xb6
        >  net/http.HandlerFunc.ServeHTTP(0x704ba6?, {0x1b44930?, 0xc000208000?}, 0x410945?)
        >       /usr/local/go/src/net/http/server.go:2136 +0x29
        >  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x1b44930, 0xc000208000}, 0xc000222100)
        >       /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:109 +0xc2
        >  net/http.HandlerFunc.ServeHTTP(0x10?, {0x1b44930?, 0xc000208000?}, 0xc000052aac?)
        >       /usr/local/go/src/net/http/server.go:2136 +0x29
        >  net/http.(*ServeMux).ServeHTTP(0x410945?, {0x1b44930, 0xc000208000}, 0xc000222100)
        >       /usr/local/go/src/net/http/server.go:2514 +0x142
        >  net/http.serverHandler.ServeHTTP({0x1b3e618?}, {0x1b44930?, 0xc000208000?}, 0x6?)
        >       /usr/local/go/src/net/http/server.go:2938 +0x8e
        >  net/http.(*conn).serve(0xc0001a23f0, {0x1b51d68, 0xc0002ea240})
        >       /usr/local/go/src/net/http/server.go:2009 +0x5f4
        >  created by net/http.(*Server).Serve in goroutine 26
        >       /usr/local/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by kimtore** [comment]
Still relevant?
